apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - "--mode=manager"
        - "--manager-pod=$(MY_POD_NAME)"
        - "--manager-namespace=$(MY_POD_NAMESPACE)"
        - "--enable-leader-election"
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: jungler/controller:latest
        name: manager
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/pki
          name: k8s-cert-dir
        - mountPath: /ca.crt
          name: ca-bundle
          subPath: ca.crt
      volumes:
      - name: k8s-cert-dir
        hostPath:
          path: /etc/kubernetes/pki
      - name: ca-bundle
        configMap:
           name: operator-ca-bundle
      terminationGracePeriodSeconds: 10
