apiVersion: operator.kubeadm.x-k8s.io/v1alpha1
kind: Operation
metadata:
  name: upgrade
spec:
  executionMode: Auto
  upgrade:
    kubernetesVersion: v1.24.1
    kubeadmVersion: v1.24.1
    kubeletVersion: v1.24.1
    kubectlVersion: v1.24.1
    #kubectlVersion: v1.23.2
    nodeIP: 10.169.180.51
    cmd: kubeadm
