//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/kubeadm/operator/errors"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaRotationOperationSpec) DeepCopyInto(out *CaRotationOperationSpec) {
	*out = *in
	if in.NodeList != nil {
		in, out := &in.NodeList, &out.NodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NewCaCert != nil {
		in, out := &in.NewCaCert, &out.NewCaCert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.NewCaKey != nil {
		in, out := &in.NewCaKey, &out.NewCaKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CaBundle != nil {
		in, out := &in.CaBundle, &out.CaBundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.NewKubeletClientCerts != nil {
		in, out := &in.NewKubeletClientCerts, &out.NewKubeletClientCerts
		*out = make(map[string]*CertPair, len(*in))
		for key, val := range *in {
			var outVal *CertPair
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(CertPair)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaRotationOperationSpec.
func (in *CaRotationOperationSpec) DeepCopy() *CaRotationOperationSpec {
	if in == nil {
		return nil
	}
	out := new(CaRotationOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertPair) DeepCopyInto(out *CertPair) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertPair.
func (in *CertPair) DeepCopy() *CertPair {
	if in == nil {
		return nil
	}
	out := new(CertPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandDescriptor) DeepCopyInto(out *CommandDescriptor) {
	*out = *in
	if in.KubeadmRenewCertificates != nil {
		in, out := &in.KubeadmRenewCertificates, &out.KubeadmRenewCertificates
		*out = new(KubeadmRenewCertsCommandSpec)
		**out = **in
	}
	if in.KubeadmUpgradeApply != nil {
		in, out := &in.KubeadmUpgradeApply, &out.KubeadmUpgradeApply
		*out = new(KubeadmUpgradeApplyCommandSpec)
		**out = **in
	}
	if in.KubeadmUpgradeNode != nil {
		in, out := &in.KubeadmUpgradeNode, &out.KubeadmUpgradeNode
		*out = new(KubeadmUpgradeNodeCommandSpec)
		**out = **in
	}
	if in.Preflight != nil {
		in, out := &in.Preflight, &out.Preflight
		*out = new(PreflightCommandSpec)
		**out = **in
	}
	if in.UpgradeKubeadm != nil {
		in, out := &in.UpgradeKubeadm, &out.UpgradeKubeadm
		*out = new(UpgradeKubeadmCommandSpec)
		**out = **in
	}
	if in.UpgradeKubeletAndKubeactl != nil {
		in, out := &in.UpgradeKubeletAndKubeactl, &out.UpgradeKubeletAndKubeactl
		*out = new(UpgradeKubeletAndKubeactlCommandSpec)
		**out = **in
	}
	if in.KubectlDrain != nil {
		in, out := &in.KubectlDrain, &out.KubectlDrain
		*out = new(KubectlDrainCommandSpec)
		**out = **in
	}
	if in.KubectlUncordon != nil {
		in, out := &in.KubectlUncordon, &out.KubectlUncordon
		*out = new(KubectlUncordonCommandSpec)
		**out = **in
	}
	if in.WriteNewRootCaToDisk != nil {
		in, out := &in.WriteNewRootCaToDisk, &out.WriteNewRootCaToDisk
		*out = new(WriteNewRootCaToDiskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RestartControllerManager != nil {
		in, out := &in.RestartControllerManager, &out.RestartControllerManager
		*out = new(RestartControllerManagerSpec)
		**out = **in
	}
	if in.RestartControlPlaneComponent != nil {
		in, out := &in.RestartControlPlaneComponent, &out.RestartControlPlaneComponent
		*out = new(RestartControlPlaneComponentSpec)
		**out = **in
	}
	if in.RestartKubeproxyAndCoredns != nil {
		in, out := &in.RestartKubeproxyAndCoredns, &out.RestartKubeproxyAndCoredns
		*out = new(RestartKubeproxyAndCorednsSpec)
		**out = **in
	}
	if in.UpdateUserAccount != nil {
		in, out := &in.UpdateUserAccount, &out.UpdateUserAccount
		*out = new(UpdateUserAccountSpec)
		**out = **in
	}
	if in.UpdateApiserverCerts != nil {
		in, out := &in.UpdateApiserverCerts, &out.UpdateApiserverCerts
		*out = new(UpdateApiserverCertsSpec)
		**out = **in
	}
	if in.RemoveOldRootCaFromDisk != nil {
		in, out := &in.RemoveOldRootCaFromDisk, &out.RemoveOldRootCaFromDisk
		*out = new(RemoveOldRootCaFromDiskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveOldCaInTokensAndSecrets != nil {
		in, out := &in.RemoveOldCaInTokensAndSecrets, &out.RemoveOldCaInTokensAndSecrets
		*out = new(RemoveOldCaInTokensAndSecretsSpec)
		**out = **in
	}
	if in.WriteNewKubeletCert != nil {
		in, out := &in.WriteNewKubeletCert, &out.WriteNewKubeletCert
		*out = new(WriteNewKubeletCertSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveOldCaFromKubeletConfig != nil {
		in, out := &in.RemoveOldCaFromKubeletConfig, &out.RemoveOldCaFromKubeletConfig
		*out = new(RemoveOldCaFromKubeletConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModifyConfigs != nil {
		in, out := &in.ModifyConfigs, &out.ModifyConfigs
		*out = new(ModifyConfigsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pass != nil {
		in, out := &in.Pass, &out.Pass
		*out = new(PassCommandSpec)
		**out = **in
	}
	if in.Fail != nil {
		in, out := &in.Fail, &out.Fail
		*out = new(FailCommandSpec)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(WaitCommandSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandDescriptor.
func (in *CommandDescriptor) DeepCopy() *CommandDescriptor {
	if in == nil {
		return nil
	}
	out := new(CommandDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateAllNewKubeletClientCertsSpec) DeepCopyInto(out *CreateAllNewKubeletClientCertsSpec) {
	*out = *in
	if in.CaRotationOperation != nil {
		in, out := &in.CaRotationOperation, &out.CaRotationOperation
		*out = new(CaRotationOperationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeList != nil {
		in, out := &in.NodeList, &out.NodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateAllNewKubeletClientCertsSpec.
func (in *CreateAllNewKubeletClientCertsSpec) DeepCopy() *CreateAllNewKubeletClientCertsSpec {
	if in == nil {
		return nil
	}
	out := new(CreateAllNewKubeletClientCertsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomOperationSpec) DeepCopyInto(out *CustomOperationSpec) {
	*out = *in
	if in.Workflow != nil {
		in, out := &in.Workflow, &out.Workflow
		*out = make([]RuntimeTaskGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomOperationSpec.
func (in *CustomOperationSpec) DeepCopy() *CustomOperationSpec {
	if in == nil {
		return nil
	}
	out := new(CustomOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailCommandSpec) DeepCopyInto(out *FailCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailCommandSpec.
func (in *FailCommandSpec) DeepCopy() *FailCommandSpec {
	if in == nil {
		return nil
	}
	out := new(FailCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlagsPatchSpec) DeepCopyInto(out *FlagsPatchSpec) {
	*out = *in
	if in.FlagsPatch != nil {
		in, out := &in.FlagsPatch, &out.FlagsPatch
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagsPatchSpec.
func (in *FlagsPatchSpec) DeepCopy() *FlagsPatchSpec {
	if in == nil {
		return nil
	}
	out := new(FlagsPatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeadmRenewCertsCommandSpec) DeepCopyInto(out *KubeadmRenewCertsCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeadmRenewCertsCommandSpec.
func (in *KubeadmRenewCertsCommandSpec) DeepCopy() *KubeadmRenewCertsCommandSpec {
	if in == nil {
		return nil
	}
	out := new(KubeadmRenewCertsCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeadmUpgradeApplyCommandSpec) DeepCopyInto(out *KubeadmUpgradeApplyCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeadmUpgradeApplyCommandSpec.
func (in *KubeadmUpgradeApplyCommandSpec) DeepCopy() *KubeadmUpgradeApplyCommandSpec {
	if in == nil {
		return nil
	}
	out := new(KubeadmUpgradeApplyCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeadmUpgradeNodeCommandSpec) DeepCopyInto(out *KubeadmUpgradeNodeCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeadmUpgradeNodeCommandSpec.
func (in *KubeadmUpgradeNodeCommandSpec) DeepCopy() *KubeadmUpgradeNodeCommandSpec {
	if in == nil {
		return nil
	}
	out := new(KubeadmUpgradeNodeCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubectlDrainCommandSpec) DeepCopyInto(out *KubectlDrainCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubectlDrainCommandSpec.
func (in *KubectlDrainCommandSpec) DeepCopy() *KubectlDrainCommandSpec {
	if in == nil {
		return nil
	}
	out := new(KubectlDrainCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubectlUncordonCommandSpec) DeepCopyInto(out *KubectlUncordonCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubectlUncordonCommandSpec.
func (in *KubectlUncordonCommandSpec) DeepCopy() *KubectlUncordonCommandSpec {
	if in == nil {
		return nil
	}
	out := new(KubectlUncordonCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyConfigsSpec) DeepCopyInto(out *ModifyConfigsSpec) {
	*out = *in
	if in.FlagsPatchs != nil {
		in, out := &in.FlagsPatchs, &out.FlagsPatchs
		*out = make([]FlagsPatchSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyConfigsSpec.
func (in *ModifyConfigsSpec) DeepCopy() *ModifyConfigsSpec {
	if in == nil {
		return nil
	}
	out := new(ModifyConfigsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operation) DeepCopyInto(out *Operation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operation.
func (in *Operation) DeepCopy() *Operation {
	if in == nil {
		return nil
	}
	out := new(Operation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Operation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationList) DeepCopyInto(out *OperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Operation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationList.
func (in *OperationList) DeepCopy() *OperationList {
	if in == nil {
		return nil
	}
	out := new(OperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationSpec) DeepCopyInto(out *OperationSpec) {
	*out = *in
	in.OperatorDescriptor.DeepCopyInto(&out.OperatorDescriptor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationSpec.
func (in *OperationSpec) DeepCopy() *OperationSpec {
	if in == nil {
		return nil
	}
	out := new(OperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStatus) DeepCopyInto(out *OperationStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ErrorReason != nil {
		in, out := &in.ErrorReason, &out.ErrorReason
		*out = new(errors.OperationStatusError)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStatus.
func (in *OperationStatus) DeepCopy() *OperationStatus {
	if in == nil {
		return nil
	}
	out := new(OperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorDescriptor) DeepCopyInto(out *OperatorDescriptor) {
	*out = *in
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeOperationSpec)
		**out = **in
	}
	if in.RenewCertificates != nil {
		in, out := &in.RenewCertificates, &out.RenewCertificates
		*out = new(RenewCertificatesOperationSpec)
		**out = **in
	}
	if in.CaRotaion != nil {
		in, out := &in.CaRotaion, &out.CaRotaion
		*out = new(CaRotationOperationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModifyConfigs != nil {
		in, out := &in.ModifyConfigs, &out.ModifyConfigs
		*out = new(ModifyConfigsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomOperation != nil {
		in, out := &in.CustomOperation, &out.CustomOperation
		*out = new(CustomOperationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorDescriptor.
func (in *OperatorDescriptor) DeepCopy() *OperatorDescriptor {
	if in == nil {
		return nil
	}
	out := new(OperatorDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PassCommandSpec) DeepCopyInto(out *PassCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PassCommandSpec.
func (in *PassCommandSpec) DeepCopy() *PassCommandSpec {
	if in == nil {
		return nil
	}
	out := new(PassCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreflightCommandSpec) DeepCopyInto(out *PreflightCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreflightCommandSpec.
func (in *PreflightCommandSpec) DeepCopy() *PreflightCommandSpec {
	if in == nil {
		return nil
	}
	out := new(PreflightCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveOldCaFromKubeletConfigSpec) DeepCopyInto(out *RemoveOldCaFromKubeletConfigSpec) {
	*out = *in
	if in.NewCaCert != nil {
		in, out := &in.NewCaCert, &out.NewCaCert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveOldCaFromKubeletConfigSpec.
func (in *RemoveOldCaFromKubeletConfigSpec) DeepCopy() *RemoveOldCaFromKubeletConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RemoveOldCaFromKubeletConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveOldCaInTokensAndSecretsSpec) DeepCopyInto(out *RemoveOldCaInTokensAndSecretsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveOldCaInTokensAndSecretsSpec.
func (in *RemoveOldCaInTokensAndSecretsSpec) DeepCopy() *RemoveOldCaInTokensAndSecretsSpec {
	if in == nil {
		return nil
	}
	out := new(RemoveOldCaInTokensAndSecretsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveOldRootCaFromDiskSpec) DeepCopyInto(out *RemoveOldRootCaFromDiskSpec) {
	*out = *in
	if in.CaRotationOperation != nil {
		in, out := &in.CaRotationOperation, &out.CaRotationOperation
		*out = new(CaRotationOperationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveOldRootCaFromDiskSpec.
func (in *RemoveOldRootCaFromDiskSpec) DeepCopy() *RemoveOldRootCaFromDiskSpec {
	if in == nil {
		return nil
	}
	out := new(RemoveOldRootCaFromDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenewCertificatesOperationSpec) DeepCopyInto(out *RenewCertificatesOperationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenewCertificatesOperationSpec.
func (in *RenewCertificatesOperationSpec) DeepCopy() *RenewCertificatesOperationSpec {
	if in == nil {
		return nil
	}
	out := new(RenewCertificatesOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartControlPlaneComponentSpec) DeepCopyInto(out *RestartControlPlaneComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartControlPlaneComponentSpec.
func (in *RestartControlPlaneComponentSpec) DeepCopy() *RestartControlPlaneComponentSpec {
	if in == nil {
		return nil
	}
	out := new(RestartControlPlaneComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartControllerManagerSpec) DeepCopyInto(out *RestartControllerManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartControllerManagerSpec.
func (in *RestartControllerManagerSpec) DeepCopy() *RestartControllerManagerSpec {
	if in == nil {
		return nil
	}
	out := new(RestartControllerManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartKubeproxyAndCorednsSpec) DeepCopyInto(out *RestartKubeproxyAndCorednsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartKubeproxyAndCorednsSpec.
func (in *RestartKubeproxyAndCorednsSpec) DeepCopy() *RestartKubeproxyAndCorednsSpec {
	if in == nil {
		return nil
	}
	out := new(RestartKubeproxyAndCorednsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTask) DeepCopyInto(out *RuntimeTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTask.
func (in *RuntimeTask) DeepCopy() *RuntimeTask {
	if in == nil {
		return nil
	}
	out := new(RuntimeTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskGroup) DeepCopyInto(out *RuntimeTaskGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskGroup.
func (in *RuntimeTaskGroup) DeepCopy() *RuntimeTaskGroup {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeTaskGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskGroupList) DeepCopyInto(out *RuntimeTaskGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeTaskGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskGroupList.
func (in *RuntimeTaskGroupList) DeepCopy() *RuntimeTaskGroupList {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeTaskGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskGroupSpec) DeepCopyInto(out *RuntimeTaskGroupSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.Selector.DeepCopyInto(&out.Selector)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskGroupSpec.
func (in *RuntimeTaskGroupSpec) DeepCopy() *RuntimeTaskGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskGroupStatus) DeepCopyInto(out *RuntimeTaskGroupStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ErrorReason != nil {
		in, out := &in.ErrorReason, &out.ErrorReason
		*out = new(errors.RuntimeTaskGroupStatusError)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskGroupStatus.
func (in *RuntimeTaskGroupStatus) DeepCopy() *RuntimeTaskGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskList) DeepCopyInto(out *RuntimeTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskList.
func (in *RuntimeTaskList) DeepCopy() *RuntimeTaskList {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskSpec) DeepCopyInto(out *RuntimeTaskSpec) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]CommandDescriptor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskSpec.
func (in *RuntimeTaskSpec) DeepCopy() *RuntimeTaskSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskStatus) DeepCopyInto(out *RuntimeTaskStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ErrorReason != nil {
		in, out := &in.ErrorReason, &out.ErrorReason
		*out = new(errors.RuntimeTaskStatusError)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskStatus.
func (in *RuntimeTaskStatus) DeepCopy() *RuntimeTaskStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTaskTemplateSpec) DeepCopyInto(out *RuntimeTaskTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTaskTemplateSpec.
func (in *RuntimeTaskTemplateSpec) DeepCopy() *RuntimeTaskTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeTaskTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateApiserverCertsSpec) DeepCopyInto(out *UpdateApiserverCertsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateApiserverCertsSpec.
func (in *UpdateApiserverCertsSpec) DeepCopy() *UpdateApiserverCertsSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateApiserverCertsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateUserAccountSpec) DeepCopyInto(out *UpdateUserAccountSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateUserAccountSpec.
func (in *UpdateUserAccountSpec) DeepCopy() *UpdateUserAccountSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateUserAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeKubeadmCommandSpec) DeepCopyInto(out *UpgradeKubeadmCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeKubeadmCommandSpec.
func (in *UpgradeKubeadmCommandSpec) DeepCopy() *UpgradeKubeadmCommandSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeKubeadmCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeKubeletAndKubeactlCommandSpec) DeepCopyInto(out *UpgradeKubeletAndKubeactlCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeKubeletAndKubeactlCommandSpec.
func (in *UpgradeKubeletAndKubeactlCommandSpec) DeepCopy() *UpgradeKubeletAndKubeactlCommandSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeKubeletAndKubeactlCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeOperationSpec) DeepCopyInto(out *UpgradeOperationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeOperationSpec.
func (in *UpgradeOperationSpec) DeepCopy() *UpgradeOperationSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitCommandSpec) DeepCopyInto(out *WaitCommandSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitCommandSpec.
func (in *WaitCommandSpec) DeepCopy() *WaitCommandSpec {
	if in == nil {
		return nil
	}
	out := new(WaitCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteNewKubeletCertSpec) DeepCopyInto(out *WriteNewKubeletCertSpec) {
	*out = *in
	if in.CaRotationOperation != nil {
		in, out := &in.CaRotationOperation, &out.CaRotationOperation
		*out = new(CaRotationOperationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteNewKubeletCertSpec.
func (in *WriteNewKubeletCertSpec) DeepCopy() *WriteNewKubeletCertSpec {
	if in == nil {
		return nil
	}
	out := new(WriteNewKubeletCertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteNewRootCaToDiskSpec) DeepCopyInto(out *WriteNewRootCaToDiskSpec) {
	*out = *in
	if in.CaRotationOperation != nil {
		in, out := &in.CaRotationOperation, &out.CaRotationOperation
		*out = new(CaRotationOperationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteNewRootCaToDiskSpec.
func (in *WriteNewRootCaToDiskSpec) DeepCopy() *WriteNewRootCaToDiskSpec {
	if in == nil {
		return nil
	}
	out := new(WriteNewRootCaToDiskSpec)
	in.DeepCopyInto(out)
	return out
}
